### PR TITLE
Use mapbox hpp skel

### PR DESCRIPTION
**Pull request by delfrrr**
Based on PR from @flippmoke #3

+ plus fixing builds
+ plus removing (for now) coverage and code style check facilities

### CODE REVIEW

**Comment by delfrrr** [comment]
@flippmoke what was the motivation to change `Delaunator` class to struct?

**Comment by flippmoke** [comment]
@delfrrr the original thought was to make it a struct and then simply migrate over time the methods to act on it instead of acting on private values within the struct. The reason for this was that there is very limited information that is actually required at the end and some variables are just needed within the struct itself. If you wish to make it back into a class that is fine, but I think currently the struct stores too much extra information that isn't required after the algorithm is run.

**Comment by delfrrr** [comment]
@flippmoke ah so you suggest instead of using private properties pass them as references to the parameters of the methods? and move methods to static functions? so at the end it can be just a static function which returns struct with triangles and half-edges?

I think It's not bad idea; but it's also true for JS version (cc @mourner); I'm trying to keep close to JS version so I can move updates to cpp version.

I added separate issue #7 for this. For now having struct with private members does not make sense for me.

**Comment by delfrrr** [comment]
@flippmoke any particular reason for `std::vector<double> const& coords` instead of `const std::vector<double> &coords`?

**Pull request merged**
